# scopes.py
# --- DOM adapters: connect these to your WebEngine or lxml layer
def _query_css(base_node, css): ...
def _query_xpath(base_node, xp): ...
def _get_text(node): ...
def _get_inner_html(node): ...
def _get_attr(node, name): ...
def _prefer_set(nodes_a, nodes_b): ...
def _combine_nodes(nodes_a, nodes_b): ...
def _resolve_path(root, path_fingerprint): ...
def _find_by_near_text(root, text_hint): ...
# ----------------------------------------------

def resolve_scope_nodes(page_dom, scope, *, item_nodes=None, anchor_cache=None):
    ...

def evaluate_selector(base_node, selector, expect="one"):
    ...

def extract_value(nodes, mode, attr):
    ...
